### ISSUE TITLE
Segfault at start up when loading a patch and getting messages at the same time.

### ISSUE THREAD

**Issue by loki42** [drobilla/ingen#38]
When sending messages to Ingen at start up while loading a patch Ingen segfaults. This is with latest code / dependencies.
If you load the patch first, then wait for send messages after everything is done, no crash, if you send it during start up crash. Ingen shouldn't accept connections until it's done loading the initial preset, unless there's a proper fix for this.

```
_:b150
	a patch:Set ;
	patch:subject <ingen:/main/amp_nam2/output_level> ;
	patch:property midi:binding ;
	patch:value [
		a midi:Controller ;
		midi:controllerNumber "35"^^xsd:int
	] .

_:b152
	a patch:Patch ;
	patch:subject <ingen:/main/amp_nam1/input_level> ;
	patch:remove [
		midi:binding patch:wildcard
	] ;
	patch:add [] .

Thread 3 "ingen" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xfffff704f180 (LWP 37272)]
ingen::server::ClientUpdate::put_port (this=0xffffec00a9f8, port=0x70) at ../src/server/ClientUpdate.cpp:55
55		const URIs& uris = port->bufs().uris();
(gdb) bt
#0  ingen::server::ClientUpdate::put_port (this=0xffffec00a9f8, port=0x70) at ../src/server/ClientUpdate.cpp:55
#1  0x0000fffff78c79d8 in ingen::server::ClientUpdate::put_graph (this=this@entry=0xffffec00a9f8, graph=0xfffff0261010)
    at ../src/server/ClientUpdate.cpp:100
#2  0x0000fffff78ab658 in ingen::server::events::Get::pre_process (this=0xffffec00a8d0) at ../src/server/events/Get.cpp:72
#3  0x0000fffff78f3d68 in ingen::server::PreProcessor::run (this=0xaaaaaac26500) at ../src/server/PreProcessor.cpp:221
#4  0x0000fffff7d8e9dc in ?? () from /lib/aarch64-linux-gnu/libstdc++.so.6
#5  0x0000fffff7b4ee18 in start_thread (arg=0xffffffffea87) at ./nptl/pthread_create.c:442
#6  0x0000fffff7bb7e9c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79
```

**Comment by drobilla** [comment]
Do you have a script that can repro this?

**Comment by loki42** [comment]
No but I can write one. Basically I load a preset that takes some time to load and then send any other messages (like gets) during start up and it will crash. I changed some of the start up code to reduce this but I'll change it back to the standard one and write a script so you can have a comprehensive fix. My fix was just not to accept network connections until the initial patch had finished loading.

**Comment by drobilla** [comment]
See the other ticket, but recording the data on the wire would be an easy way to provide repros for basically any issue and it would only need to be implemented once.  I may not be able to replay such a "log" exactly because of plugins or whatever other reason, but it's a lot better than nothing, and it's easy to transform into a test case so once something is fixed, it will stay fixed forever.  I suppose this could be implemented in the server itself, but I'm not sure that's the way that makes sense with your architecture.
